foreground            #000000
background            #F6F6F6
selection_foreground  #F6F6F6
selection_background  #000000
cursor                #000000
cursor_text_color     #F6F6F6

# Black (N4)
color0  #D8D8D8
color8  #D8D8D8

# Red
color1  #9A0000
color9  #9A0000

# Green
color2  #5F9A00
color10 #5F9A00

# Yellow
color3  #9A7100
color11 #9A7100

# Blue
color4  #00679A
color12 #00679A

# Magenta (Pink)
color5  #9A0074
color13 #9A0074

# Cyan
color6  #008B9A
color14 #008B9A

# White (T0)
color7  #000000
color15 #000000
