foreground            #F2F2F2
background            #141414
selection_foreground  #141414
selection_background  #F2F2F2
cursor                #F2F2F2
cursor_text_color     #141414

# Black (N4)
color0  #383838
color8  #383838

# Red
color1  #FF7272
color9  #FF7272

# Green
color2  #A8FF72
color10 #A8FF72

# Yellow
color3  #FFDE72
color11 #FFDE72

# Blue
color4  #72BBFF
color12 #72BBFF

# Magenta (Pink)
color5  #FF72F6
color13 #FF72F6

# Cyan
color6  #72E0FF
color14 #72E0FF

# White (T0)
color7  #F2F2F2
color15 #F2F2F2
