palette = "whiskers_panther"


add_newline = true


[directory]

truncation_symbol = '../'


[character]

success_symbol = "[](green)"

error_symbol = "[](red)"


[git_branch]

symbol = '󰘬 '


[package]

style = "tangerine bold"



[palettes.whiskers_panther]

# Starship Default Colors Replaced With Whiskers

yellow = "#FFE072"

blue = "#A5CEFF"

cyan = "#A5CEFF"

red = "#FF8C7C"

purple = "#FFAAF5"

green = "#B1E380"

white = "#FFEEE2"

black = "#000000"

# Whiskers Colors

banana = "#FFE072"

blueberry = "#A5CEFF"

cherry = "#FF8C7C"

grape = "#FFAAF5"

kiwi = "#B1E380"

tangerine = "#FFB26C"

neutral = "#000000"

neutral_two = "#0E0600"

neutral_three = "#140800"

neutral_for = "#1B0B00"

neutral_five = "#210D00"

neutral_six = "#301300"

neutral_seven = "#401A00"

neutral_eight = "#502000"

text = "#FFEEE2"

text_two = "#E5D2C5"

text_three = "#CFBBAD"

text_for = "#B5A8A0"


[palettes.whiskers_lynx]

# Starship Default Colors Replaced With Whiskers

yellow = "#A87B0A"

blue = "#5284BE"

cyan = "#5284BE"

red = "#B43A2A"

purple = "#7D0E70"

green = "#6A9534"

white = "#FFFCF8"

black = "#3E1900"

# Whiskers Colors

banana = "#A87B0A"

blueberry = "#5284BE"

cherry = "#B43A2A"

grape = "#7D0E70"

kiwi = "#6A9534"

tangerine = "#C15D01"

neutral = "#FFFCF8"

neutral_two = "#FFF9F0"

neutral_three = "#FFF5E7"

neutral_for = "#FFF3E2"

neutral_five = "#FFF1DD"

neutral_six = "#FFF0DA"

neutral_seven = "#FFEFD7"

neutral_eight = "#FFECCF"

text = "#3E1900"

text_two = "#865C3A"

text_three = "#A17A5A"

text_for = "#AE917C" 
