general:
  # Whether to automatically focus windows underneath the cursor.
  focus_follows_cursor: true

  # Whether to jump the cursor between windows focused by the WM.
  cursor_follows_focus: true

  # Whether to switch back and forth between the previously focused workspace
  # when focusing the current workspace.
  toggle_workspace_on_refocus: false

  # Whether to show floating windows as always on top.
  show_floating_on_top: true

  # Amount to move floating windows by (eg. when using `alt+<hjkl>` on a floating window)
  floating_window_move_amount: "5%"

  # Whether to center new floating windows.
  center_new_floating_windows: false

  # *Strongly* recommended to set to 'false'. Whether to globally enable/disable
  # window transition animations (on minimize, close, etc). Set to 'unchanged'
  # to make no setting changes.
  window_animations: "unchanged"

gaps:
  # Gap between adjacent windows.
  inner_gap: "8px"

  # Gap between windows and the screen edge.
  outer_gap: "8px"

# Highlight active/inactive windows with a colored border.
# ** Exclusive to Windows 11 due to API limitations.
focus_borders:
  active:
    enabled: true
    color: "#B1E380"

  inactive:
    enabled: true
    color: "#0E0600"

bar:
  height: "42px"
  position: "bottom"
  opacity: 1.0
  background: "#0E0600"
  foreground: "#FFEEE2"
  font_family: "JetBrainsMono NF"
  font_size: "12px"
  padding: "8px 6px 8px 6px"
  offset_x: "8"
  offset_y: "-8"
  border_radius: "8"
  border_width: "1"
  border_color: "#140800"
  components_left:
    - type: "clock"
      padding: "2px 8px 2px 8px"
      margin: "0 8px 0 0"
      time_formatting: "HH:mm"
      background: "#1B0B00"
    - type: "workspaces"
      focused_workspace_background: "transparent"
      focused_workspace_foreground: "#B1E380"
      displayed_workspace_background: "transparent"
      displayed_workspace_foreground: "#B1E380"
      default_workspace_background: "transparent"
      background: "#1B0B00"
      padding: "2px 8px 2px 8px"
  components_center:
    - type: "music"
      label_not_playing: "..."
      label_paused: "󰠃 {artist_name} -  {song_title}"
      label_playing: "󰠃 {artist_name} -  {song_title}"
      max_title_length: 24
      max_artist_length: 24
  components_right:
    - type: "system tray"
      padding: "3px 8px 3px 8px"
      time_formatting: "HH:mm"
      background: "#1B0B00"
    

workspaces:
  - name: "1"
    display_name: "  Main"
    bind_to_monitor: 1
    keep_alive: true
  - name: "2"
    display_name: "  Browsing"
    bind_to_monitor: 1
    keep_alive: true
  - name: "3"
    display_name: "  Utility"
    bind_to_monitor: 1
    keep_alive: true
  - name: "4"
    display_name: "  Social"
    bind_to_monitor: 1
    keep_alive: true
  - name: "5"
    display_name: "  Random"
    bind_to_monitor: 1
    keep_alive: true
  - name: "6"
    display_name: "  Main"
    bind_to_monitor: 2
    keep_alive: true
  - name: "7"
    display_name: "  Browsing"
    bind_to_monitor: 2
    keep_alive: true
  - name: "8"
    display_name: "  Utility"
    bind_to_monitor: 2
    keep_alive: true
  - name: "9"
    display_name: "  Social"
    bind_to_monitor: 2
    keep_alive: true

window_rules:
  # Task Manager requires admin privileges to manage and should be ignored unless running
  # the WM as admin.
  - command: "ignore"
    match_process_name: "/Taskmgr|ScreenClippingHost/"

  - command: "ignore"
    match_process_name: "whiskers-launcher"

  - command: "set floating"
    match_process_name: "whiskers-launcher"

  # Launches system dialogs as floating by default (eg. File Explorer save/open dialog).
  - command: "set floating"
    match_class_name: "#32770"

  # Do not manage picture-in-picture windows for browsers. Note that the default is for
  # English; change `match_title` to the window's title if you use another language.
  - command: "ignore"
    match_title: "[Pp]icture.in.[Pp]icture"
    match_class_name: "Chrome_WidgetWin_1|MozillaDialogClass"

  # Some applications (eg. Steam) have borders that extend past the normal border size.
  - command: "resize borders 0px -7px -7px -7px"
    match_process_name: "steam"

binding_modes:
  - name: "resize"
    keybindings:
      # Resize focused window by a percentage or pixel amount.
      - command: "resize width -2%"
        bindings: ["H", "Left"]
      - command: "resize width +2%"
        bindings: ["L", "Right"]
      - command: "resize height +2%"
        bindings: ["K", "Up"]
      - command: "resize height -2%"
        bindings: ["J", "Down"]
      # Press enter/escape to return to default keybindings.
      - command: "binding mode none"
        bindings: ["Escape", "Enter"]

keybindings:
  # Shift focus in a given direction.
  - command: "focus left"
    bindings: ["Alt+H", "Alt+Left"]
  - command: "focus right"
    bindings: ["Alt+L", "Alt+Right"]
  - command: "focus up"
    bindings: ["Alt+K"]
  - command: "focus down"
    bindings: ["Alt+J"]

  # Move focused window in a given direction.
  - command: "move left"
    bindings: ["Alt+Shift+H", "Alt+Shift+Left"]
  - command: "move right"
    bindings: ["Alt+Shift+L", "Alt+Shift+Right"]
  - command: "move up"
    bindings: ["Alt+Shift+K", "Alt+Shift+Up"]
  - command: "move down"
    bindings: ["Alt+Shift+J", "Alt+Shift+Down"]

  # Resize focused window by a percentage or pixel amount.
  - command: "resize width -2%"
    binding: "Alt+U"
  - command: "resize width +2%"
    binding: "Alt+P"
  - command: "resize height +2%"
    binding: "Alt+O"
  - command: "resize height -2%"
    binding: "Alt+I"

  # As an alternative to the resize keybindings above, resize mode enables resizing via
  # HJKL or arrow keys. The binding mode is defined above with the name "resize".
  - command: "binding mode resize"
    binding: "Alt+R"

  # Change tiling direction. This determines where new tiling windows will be inserted.
  - command: "tiling direction toggle"
    binding: "Alt+V"

  # Change focus between floating / tiling windows.
  - command: "focus mode toggle"
    binding: "Alt+F"

  # Change the focused window to be floating / tiling.
  - command: "toggle floating"
    binding: "Alt+Shift+Space"

  # Change the focused window to be maximized / unmaximized.
  - command: "toggle maximized"
    binding: "Alt+X"

  # Minimize focused window.
  - command: "set minimized"
    binding: "Alt+M"

  # Close focused window.
  - command: "close"
    binding: "Alt+Q"

  # Kill GlazeWM process safely.
  - command: "exit wm"
    binding: "Alt+Shift+E"

  # Re-evaluate configuration file.
  - command: "reload config"
    binding: "Alt+Shift+R"

  # Launch CMD terminal (alternatively `exec wt` or `exec %ProgramFiles%/Git/git-bash.exe`
  # to start Windows Terminal and Git Bash respectively.
  - command: "exec powershell"
    binding: "Alt+T"

  # Focus the workspace that last had focus.
  - command: "focus workspace recent"
    binding: "Alt+Y"

  # Focus the next/previous workspace defined in `workspaces` config.
  - command: "focus workspace next"
    binding: "Alt+T"
  - command: "focus workspace prev"
    binding: "Alt+Shift+T"

  # Change focus to a workspace defined in `workspaces` config.
  - command: "focus workspace 1"
    binding: "Alt+1"
  - command: "focus workspace 2"
    binding: "Alt+2"
  - command: "focus workspace 3"
    binding: "Alt+3"
  - command: "focus workspace 4"
    binding: "Alt+4"
  - command: "focus workspace 5"
    binding: "Alt+5"
  - command: "focus workspace 6"
    binding: "Alt+6"
  - command: "focus workspace 7"
    binding: "Alt+7"
  - command: "focus workspace 8"
    binding: "Alt+8"
  - command: "focus workspace 9"
    binding: "Alt+9"

  # Move focused window to a workspace defined in `workspaces` config.
  - commands: ["move to workspace 1", "focus workspace 1"]
    binding: "Alt+Shift+1"
  - commands: ["move to workspace 2", "focus workspace 2"]
    binding: "Alt+Shift+2"
  - commands: ["move to workspace 3", "focus workspace 3"]
    binding: "Alt+Shift+3"
  - commands: ["move to workspace 4", "focus workspace 4"]
    binding: "Alt+Shift+4"
  - commands: ["move to workspace 5", "focus workspace 5"]
    binding: "Alt+Shift+5"
  - commands: ["move to workspace 6", "focus workspace 6"]
    binding: "Alt+Shift+6"
  - commands: ["move to workspace 7", "focus workspace 7"]
    binding: "Alt+Shift+7"
  - commands: ["move to workspace 8", "focus workspace 8"]
    binding: "Alt+Shift+8"
  - commands: ["move to workspace 9", "focus workspace 9"]
    bindings: ["Alt+Shift+9"]
