#!/usr/bin/env python3

import subprocess, json

dnd = subprocess.run(["swaync-client", "-D"], capture_output=True, text=True).stdout.strip() == "true"

if dnd:
    print(json.dumps({"text": f"󰂛  Off"}),flush=True)
    exit(0)


count = subprocess.run(["swaync-client", "-c"], capture_output=True, text=True).stdout.strip()
symbol = "" if count == "0" else ""

print(json.dumps({"text": symbol}),flush=True)
