# Commands
$terminal = wezterm
$fileManager = nautilus
$whiskers-launcher = WEBKIT_DISABLE_COMPOSITING_MODE=1 whiskers-launcher
$open-config = code ~/.config/hypr/


$MOD = SUPER

#========================== Screens ==============================#
bind = , XF86MonBrightnessUp, exec, brightnessctl s +10% && ~/.config/hypr/scripts/kbbacklight --inc
bind = , XF86MonBrightnessDown, exec, brightnessctl s 10%- && ~/.config/hypr/scripts/kbbacklight --dec

#======================= Apps ========================#
bind = Control_L, Space, exec, $whiskers-launcher
bind = $MOD, t, exec, $terminal
bind = $MOD, Print, exec, hyprshot -m output --silent -c --output-folder ~/Pictures/screenshots/
bind = $MOD SHIFT, Print, exec, hyprshot -m window --output-folder ~/Pictures/screenshots/
bind = $MOD Control_L, PRINT, exec, hyprshot -m region --output-folder ~/Pictures/screenshots/
bind = $MOD, E, exec, $fileManager
bind = $MOD, B, exec, blueman-manager
bind = $MOD, P, exec, pavucontrol



#======================= Window ===========================#
bind = SUPER, Q, killactive
bind = $MOD, left, movewindow,l
bind = $MOD, right, movewindow,r
bind = $MOD, up, movewindow,u
bind = $MOD, down, movewindow,d
bind = $MOD SHIFT, left, movefocus, l
bind = $MOD SHIFT, right, movefocus, r
bind = $MOD SHIFT, up, movefocus, u
bind = $MOD SHIFT, down, movefocus, d

#======================= Workspaces  ============================#
bind = $MOD, 1, workspace, 1
bind = $MOD, 2, workspace, 2
bind = $MOD, 3, workspace, 3
bind = $MOD, 4, workspace, 4
bind = $MOD, 5, workspace, 5
bind = $MOD, 6, workspace, 6
bind = $MOD, 7, workspace, 7
bind = $MOD, 8, workspace, 8
bind = $MOD, 9, workspace, 9
bind = $MOD, 0, workspace, 10
bind = $MOD SHIFT, 1, movetoworkspace, 1
bind = $MOD SHIFT, 2, movetoworkspace, 2
bind = $MOD SHIFT, 3, movetoworkspace, 3
bind = $MOD SHIFT, 4, movetoworkspace, 4
bind = $MOD SHIFT, 5, movetoworkspace, 5
bind = $MOD SHIFT, 6, movetoworkspace, 6
bind = $MOD SHIFT, 7, movetoworkspace, 7
bind = $MOD SHIFT, 8, movetoworkspace, 8
bind = $MOD SHIFT, 9, movetoworkspace, 9
bind = $MOD SHIFT, 0, movetoworkspace, 10


#======================= Media  ============================#
bind = , XF86AudioRaiseVolume, exec, pamixer -i 5 && pamixer --unmute
bind = , XF86AudioLowerVolume, exec, pamixer -d 5 && pamixer --unmute
bind = , XF86AudioMicMute, exec, pamixer --default-source -m
bind = , XF86AudioMute, exec, pamixer -t 
bind = , XF86AudioPlay, exec, playerctl play-pause
bind = , XF86AudioPause, exec, playerctl play-pause
bind = , XF86AudioNext, exec, playerctl next
bind = , XF86AudioPrev, exec, playerctl previous

#======================= Night Light ===========================#
bind = $MOD, N, exec, hyprshade toggle custom-blue-light


#======================= Other  ============================#
bind = $MOD, C, exec, $open-config

# Scroll through existing workspaces with mainMod + scroll
bind = $MOD, mouse_down, workspace, e+1
bind = $MOD, mouse_up, workspace, e-1

# Move/resize windows with mainMod + LMB/RMB and dragging
bindm = $MOD, mouse:272, movewindow
bindm = $MOD, mouse:273, resizewindow

bind = $MOD, L, exec, hyprlock
