# Comes by default...
windowrulev2 = suppressevent maximize, class:.*

# Disables border and blur for file selection dialogs
windowrulev2 = noborder,class:(Xdg-desktop-portal-gtk)
windowrulev2 = noblur,class:(Xdg-desktop-portal-gtk)

# Disables border on Whiskers Launcher
windowrulev2 = noborder, class:(whiskers-launcher),title:(Whiskers Launcher)
windowrulev2 = center, class:(whiskers-launcher),title:(Whiskers Launcher)
windowrulev2 = rounding 0, class:(whiskers-launcher),title:(Whiskers Launcher)
windowrulev2 = noblur, class:(whiskers-launcher),title:(Whiskers Launcher)
windowrulev2 = noanim, class:(whiskers-launcher),title:(Whiskers Launcher)

# Disables border on Whiskers Launcher
windowrulev2 = noborder, class:(Tigris-launcher),title:(tigris-launcher)
windowrulev2 = center, class:(Tigris-launcher),title:(tigris-launcher)
windowrulev2 = rounding 0, class:(Tigris-launcher),title:(tigris-launcher)
windowrulev2 = noblur, class:(Tigris-launcher),title:(tigris-launcher)
windowrulev2 = noanim, class:(Tigris-launcher),title:(tigris-launcher)

# Disables border on Whiskers Launcher
windowrulev2 = noborder, class:(tigris-launcher),title:(tigris-launcher)
windowrulev2 = center, class:(tigris-launcher),title:(tigris-launcher)
windowrulev2 = rounding 0, class:(tigris-launcher),title:(tigris-launcher)
windowrulev2 = noblur, class:(tigris-launcher),title:(tigris-launcher)
windowrulev2 = noanim, class:(tigris-launcher),title:(tigris-launcher)


# Disable blur on brave
windowrulev2 = noblur, class:(Brave-browser)

# Blurs Waybar
# layerrule = blur,waybar