#!/bin/python

import subprocess
import argparse
from pathlib import Path

parser = argparse.ArgumentParser(description="Set Wallpaper")
parser.add_argument("wallpaper", type=Path)

args = parser.parse_args()

if not args.wallpaper.exists():
    print("Invalid Path")
    exit(1)

wallpaper_path = args.wallpaper.resolve()

subprocess.run(f"cp {wallpaper_path} ~/.config/wallpaper", shell=True, stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
subprocess.run("killall swaybg", shell=True, stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
subprocess.run("swaybg -i ~/.config/wallpaper &", shell=True, stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
