hl.on("hyprland.start", function()
	hl.exec_cmd("/usr/lib/pam_kwallet_init")
	hl.exec_cmd("/usr/lib/polkit-kde-authentication-agent-1")
	hl.exec_cmd("waybar")
	hl.exec_cmd("mako")
	hl.exec_cmd("hyprpaper")
	hl.exec_cmd("hypridle")
	hl.exec_cmd("nm-applet --indicator")
	hl.exec_cmd("blueman-applet")
	hl.exec_cmd("udiskie --tray")
	hl.exec_cmd("wl-paste --watch cliphist store")
	hl.exec_cmd("steam -silent")
	hl.exec_cmd("flatpak run dev.vencord.Vesktop --start-minimized")
	hl.exec_cmd("flatpak run com.stremio.Service")
	hl.exec_cmd("kdeconnect-indicator")
end)
